### ISSUE TITLE
Не вводится дефолтный пароль в консоли

### ISSUE THREAD

**Issue by DaemoncheG** [ndra/infuso#4]
Я создал lamp, скопировал в рабочую папку копию infuso с githab, дал рекурсивно права 777 на всякий случай, зашел на тестовый сайт с infuso по адресу http://mysite/mod/ ввел пароль 0000 но ничего не сработало, скрипты /mod/res/jquery-1.2.6.pack.js и /mod/res/console.js згружаются нормально. Пробовал на Chrome и FF

В чем может быть проблема?

**Comment by k4G17eYWI** [comment]
Скорее всего у тебя сессия не создается

7 июня 2013 г., 18:31 пользователь Dmitrix notifications@github.comнаписал:

> Я создал lamp, скопировал в рабочую папку копию infuso с githab, дал
> рекурсивно права 777 на всякий случай, зашел на тестовый сайт с infuso по
> адресу http://mysite/mod/ ввел пароль 0000 но ничего не сработало,
> скрипты /mod/res/jquery-1.2.6.pack.js и /mod/res/console.js згружаются
> нормально. Пробовал на Chrome и FF
> 
> В чем может быть проблема?
> 
> ## 
> 
> Reply to this email directly or view it on GitHubhttps://github.com/ndra/infuso/issues/4
> .

## 

Александр Голиков
+7 (989) 634-77-40

веб-студия ndra.ru http://www.ndra.ru/

**Comment by DaemoncheG** [comment]
Я создал index.php и протестировал там session_start(); сессии работают,
как в infuso включить принудительный вывод ошибок?

**Comment by petrgrishin** [comment]
Из разговора с Димой, выяснили, что сессии у него работают; он использовал версию инфузы 1.0.1, а эта версия протестирована. Скорее всего проблема локальная — в настройках php. 

Думаю с появлением composer-a таких проблем в будущем будет меньше!

**Comment by DaemoncheG** [comment]
Недавно опять попробовал infuso из разных веток на своем веб сервере, та же самая проблема и самое обидное нигде не могу найти ошибки, непонятно что именно не хватает. На каком сервере infuso 100% работает?

**Comment by petrgrishin** [comment]
Активная ветка, где ведется разработка это `dev`

**Comment by DaemoncheG** [comment]
Я пробовал dev, аналогичная проблема. Скорее всего что то именно в веб сервере, но ошибок нету. Поэтому я и хочу глянуть на каком хостинге система работает нормально, возможно пойму суть. На spaceweb всё работает?

**Comment by petrgrishin** [comment]
> как включить принудительный вывод ошибок?
> 
> ``` php
> error_reporting(E_ALL);
> ini_set("display_errors", 1); 
> ```
> 
> еще можно включить
> 
> ``` php
> ini_set("display_startup_errors", 1);
> ```

**Comment by DaemoncheG** [comment]
Я знаю как включить вывод ошибок, вывод включен, но ошибок нету.
Если я в mod/index.php сделаю ошибку нарочно, она выведется. Отсюда вывод - либо ошибки подавляются при дальнейшей работе скрипта, либо их попросту нету.

**Comment by petrgrishin** [comment]
Подавляются в дальнейшей рабо скрипта, на сколько я помню, в __autoload.php в корне модуля mod

**Comment by DaemoncheG** [comment]
Вот =), наконец то!
Теперь хоть можно искать причину.

<pre><code>Notice: Undefined index: hash in /var/www/mod/class/url.php on line 40
Notice: Undefined property: mod_app::$action in /var/www/mod/class/app.php on line 57
Notice: Undefined index: services in /var/www/mod/class/conf/conf.php on line 49
Notice: Undefined index: services in /var/www/mod/class/mod.php on line 188
Fatal error: Uncaught exception 'Exception' with message 'Service [route] not found' in /var/www/mod/class /service.php:27 Stack trace: #0 /var/www/mod/class/mod.php(374): mod_service::get('route') #1 /var/www/mod/class/url.php(296): mod->service('route') #2 /var/www/mod/class/app.php(58): mod_url->action() #3 /var/www/mod/class/action.php(121): mod_app->action() #4 /var/www/mod/class/controller/controller.php(16): mod_action::current() #5 /var/www/mod/class/console.php(30): mod_controller::redirect('/mod/') #6 /var/www/mod/index.php(11): mod_console::xindex() #7 {main} thrown in /var/www/mod/class/service.php on line 27
</code></pre>

**Comment by DaemoncheG** [comment]
Разобрался, запустить удалось из master ветки.
С помощью libastral узнал что нужно создать mod/conf/conf.xml и mod/conf/__superadmin.txt

Хотел сам пересесть на infuso, сделать ppa для ubuntu и завести блог по этому проекту, но сейчас понял что всё таки в массы это не пойдет, она только для внутреннего пользования студии ndra +)

**Comment by petrgrishin** [comment]
@DaemoncheG, на самом деле все в твоих руках, можно делать не блог, а wiki документацию, тут же на github-е. Но ты прав в массы это не пойдет, т.к. нет полного цикла разработки продукта...

Оффтоп: используй в работе PhpStorm, это даст тебе большей "маневренности между классами" в этом продукте

**Comment by DaemoncheG** [comment]
@petrgrishin я думаю это бессмысленно, всё сведется к гаданию функционала )
Например, я сейчас не представляю как указать адрес в conf.xml для обновления, ну и не совсем понятно откуда брать стабильные модули из git. А самое главное нету документации, из меня далеко не самый лучший реверс инженер.
